### ISSUE TITLE
I hope we are not trying to do the same

### ISSUE THREAD

**Issue by Sicos1977** [svengeance/QPdfSharp#2]
I just was searching for something and ran into your project on GitHub... I hope we are not building the same thing :-)

I guess that you are talking directly to the internals of QPDF and I'm just talking against the job interface.

https://github.com/Sicos1977/QPdfNet

**Comment by patrickklaeren** [comment]
There's a lot of things that achieve some parity in functionality and features, I don't think this necessitates an issue being created :)

**Comment by svengeance** [comment]
Having never done a wrapper library before, I thought QPdf was a great place to start, especially as a repayment/homage to the author for his work. I'll keep up-to-date on the internal functionality, and will be doing jobs in the near future as time permits. I don't see any problems with two packages, it'll give folks in the dotnet ecosystem some choice, and hopefully promote QPdf as a fantastic solution.
